micronaut:
  application:
    name: jwthome
  security:
    enabled: true
    authentication: bearer
    intercept-url-map:
      - pattern: "/auth/login"
        http-method: POST
        access:
          - isAnonymous()
      - pattern: "/**"
        access:
          - isAuthenticated()
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "ThisIsASecretKeyThatIs32Characters"
            validation:
              secret: "ThisIsASecretKeyThatIs32Characters"
  server:
    port: 1234
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/crudTest?currentSchema=jwt_auth
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    username: johnny
    password: mysecretpassword

logging:
  levels:
    io.micronaut.security: TRACE
    com.roxy.controllers: INFO
